name: Reportar fallo
description: Describe un fallo o problema para ayudarnos a mejorar
title: "[Bug] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        ## Contexto de la vista
        Estos campos se rellenan automáticamente si abres este formulario desde la app.
  - type: textarea
    id: what_report
    attributes:
      label: ¿Qué quieres reportar?
      description: Describe brevemente el fallo o problema.
      placeholder: "Ej.: El botón de guardar no hace nada al hacer clic."
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: ¿Qué pasos realizaste cuando sucedió?
      description: Indica los pasos para reproducir el fallo.
      value: |
        1.
        2.
        3.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: ¿Qué debería haber sucedido?
      description: Describe el comportamiento esperado.
      placeholder: "Ej.: Debería guardarse el formulario y mostrarse un mensaje de confirmación."
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## Captura de pantalla (recomendado)
        Si es posible, adjunta una captura en el cuadro de texto anterior (arrastra la imagen o pégala). **Recomendamos ocultar información sensible** (datos personales, datos de pago, etc.).
  - type: input
    id: view_title
    attributes:
      label: Título de la vista
      description: Título de la página donde ocurrió el fallo (se rellena desde la app si abres desde ahí).
      placeholder: "Ej.: Dashboard, Proyecto X, ..."
    validations:
      required: false
  - type: input
    id: view_url
    attributes:
      label: URL de la vista
      description: URL completa de la página donde ocurrió el fallo (se rellena desde la app si abres desde ahí).
      placeholder: "https://..."
    validations:
      required: false
