import type { MetadataRoute } from "next";

/**
 * Official sitemap: only /sitemap.xml is generated by Next.js (standard
 * sitemaps.org XML). robots.txt references this URL. Audit tools that report
 * "Unknown sitemap format" for other paths (e.g. sitemap_index.xml,
 * post-sitemap.xml) are probing common CMS URLs that this app does not serve.
 */
const BASE_URL =
  process.env.NEXT_PUBLIC_APP_URL ??
  (process.env.VERCEL_URL
    ? `https://${process.env.VERCEL_URL}`
    : "https://veta.pro");

const publicRoutes = [
  { path: "/", priority: 1, changeFrequency: "weekly" as const },
  { path: "/about", priority: 0.8, changeFrequency: "monthly" as const },
  { path: "/pricing", priority: 0.9, changeFrequency: "weekly" as const },
  { path: "/contact", priority: 0.8, changeFrequency: "monthly" as const },
  { path: "/legal", priority: 0.5, changeFrequency: "yearly" as const },
  { path: "/sign-in", priority: 0.6, changeFrequency: "monthly" as const },
  { path: "/sign-up", priority: 0.6, changeFrequency: "monthly" as const },
  {
    path: "/plan-base-primer-proyecto-interiorismo",
    priority: 0.7,
    changeFrequency: "monthly" as const,
  },
  {
    path: "/plan-pro-independientes-diseno-interior",
    priority: 0.7,
    changeFrequency: "monthly" as const,
  },
  {
    path: "/plan-studio-empresas-arquitectura-diseno-interior",
    priority: 0.7,
    changeFrequency: "monthly" as const,
  },
];

export default function sitemap(): MetadataRoute.Sitemap {
  return publicRoutes.map(({ path, priority, changeFrequency }) => ({
    url: `${BASE_URL}${path}`,
    lastModified: new Date(),
    changeFrequency,
    priority,
  }));
}
